services:

  postgres:
    image: postgres:16
    container_name: pg-legal
    restart: always
    environment:
      POSTGRES_DB: legal_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend-service
    container_name: spring-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/legal_assistant
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    volumes:
      - shared-data:/app/uploads
      - shared-indexes:/app/indexes

  ai-service:
    build: ./ai-service
    container_name: fastapi-ai
    ports:
      - "8000:8000"
    environment:
      OPENROUTER_API_KEY: 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
    volumes:
      - shared-data:/app/uploads
      - shared-indexes:/app/indexes

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
  shared-data:
  shared-indexes: