spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/legal_assistant
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: "TgE6rS#x7W!zLp9mF^aQ3bt7uV@jX1pZkR5dN2tC%yG0eS3rW!qB4hJ2lK9vY0a"
    access-exp-min: 30
    refresh-exp-days: 7