app.upload.dir=/app/uploads

app.index.dir=/app/indexes

app.ai.service.url=http://ai-service:8000

spring.datasource.url=jdbc:postgresql://postgres:5432/legal_assistant
spring.datasource.username=postgres
spring.datasource.password=123456



